apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: fms-web-frontend-config
  namespace: "service"
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT