apiVersion: "v1"
kind: "Service"
metadata:
  name: "fms-web-service"
  namespace: "service"
  labels:
    app-type: "fms-web"
  annotations:
    # GKE specific annotations for better load balancing
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  selector:
    app-type: "fms-web"